# Default values for shipments-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxReplicaCount: 2

appLabel: xxxxxxx
ciEnvironment: xxxxxxx

image:
  repository: gascregistry.azurecr.io/rtl/sche/odmg/corp/corp/ccc/rsc
  tag: 1.0.0
  version: 1
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  name: lpn
  port: 3000
  targetPort: 3000

enviroments:
  ADDRESS: xxxxxx
  NODE_ENV: xxxxx

secret:
  name: xxxxxx
  registry: xxxxxx
  username: xxxxxx
  password: xxxxxx
  email: xxxxxx

getsecrets:
  tenantId: xxxxxxxx
  client: xxxxxxxx
  key: xxxxxxxx
  vaultBaseUrl: xxxxxxxx
  secretKeys: xxxxxxxx

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# hostAliases allows the modification of the hosts file inside a container
hostAliases: []
 # - ip: "xx.xx.xx.xx"
 #   hostnames:
 #   - "xxxxxx.falabella.cl"

nodeSelector: {}

tolerations: []

affinity: {}

# Valores para la configuracion del inyector de Istio
istio:
  enabled: true
  virtualservice:
    api_name: customer-orders
    service: "lpn"
    prefix: "/lpn"
    rewrite:
      uri: "/"
    host: "*"
    domain: ""
  gateway:
    name: "global-gateway.istio-system"