apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    app: {{ .Values.appLabel }}
    version: "v{{ .Values.image.version }}"
    app.kubernetes.io/name: {{ include "helmchart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - "{{ .Values.istio.virtualservice.host }}{{ .Values.istio.virtualservice.domain }}"
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.virtualservice.prefix }}
    rewrite:
      uri: {{ .Values.istio.virtualservice.rewrite.uri }}
    route:
    - destination:
        host: {{ include "helmchart.fullname" . }}
        port:
          number: {{ .Values.service.port }}
